### ISSUE TITLE
Remove T : class constraint on Colleciton<T>

### ISSUE THREAD

**Issue by jfoshee** [FuturistiCoder/LiteDB.Realtime#8]
Would it be possible to remove the `T : class` constraint on `ISubscriptionBuilder.Collection<T>(string collection)`?

LiteDB does not make this requirement of the Document types.  So it makes it awkward when generalizing.

Thanks for your extension to LiteDB! Pretty cool!

**Comment by FuturistiCoder** [comment]
Thanks for your suggestion. Fixed in v1.1.1
