### ISSUE TITLE
Add `Collection<T>()` (use default name)

### ISSUE THREAD

**Issue by jfoshee** [FuturistiCoder/LiteDB.Realtime#9]
Would it be possible to add an implementation of `ISubscriptionBuilder.Collection<T>()` that does not require an argument?

In that case just use the default name for the collection based on the type `T`?

In the mean time I find myself doing this:

```c#
// HACK: Get the collection name which is required by Realtime.Collection
var collectionName = database.GetCollection<T>().Name;
var observable = database.Realtime.Collection<T>(collectionName);
```

Thanks!

**Comment by FuturistiCoder** [comment]
Thanks for your suggestion. Fixed in #8
